### PR TITLE
Self-documented Makefile with target help

### PR DESCRIPTION
**Pull request by lithrel**
This PR adds a target `make help` that displays a self-documented help message.  
The goal is to enhance discoverability, limit documentation back-and-forth, and be more welcoming to newcomers.

## Make help

Screenshot 2020-07-13 at 09 24 03

Two more messages can appear, if there's no `Makefile.include` file, and if the directory `persistence/app` does not exist

Screenshot 2020-07-13 at 10 37 52

## Self-documented

The `help` target reads comments starting with `##` on targets and variables in the `Makefile` (and `Makefile.include`) and displays them in alphabetical order.
For example:
```makefile
## Docker compose file used
DOCKER_COMPOSE_FILE ?= docker-compose.yml

## Display this help message
.PHONY: help
help:
```
will display
```console
Available variables:
  DOCKER_COMPOSE_FILE        Docker compose file used         [docker-compose.yml]

Available targets:
  help            Display this help message
```

Using `##` instead of a simple `#` allows us to decide what will appear in the help message while still commenting the rest of the code without side-effect.

## Tests

Use `make help` to display help.

### CODE REVIEW

**Comment by comzeradd** [comment]
Love it :smile: 

Works great, but I'm getting an error:
`awk: cmd. line:1: warning: regexp escape sequence `\_' is not a known regexp operator`

It displays twice, right after `Available variables:` and `Available targets:`

**Comment by lithrel** [comment]
> but I'm getting an error:

Of course there's different implementations of `awk` on osx and linux, of course :sob: gonna find a double fix :ok_hand:

**Comment by lithrel** [comment]
@comzeradd  `gawk` was unhappy, but `\` was useless, now `mawk` `gawk` and any antique macos is using seem happy :)

**Review by comzeradd — APPROVED** [review]
Looks great :100:

**Pull request merged**
